### ISSUE TITLE
Different Hex value for Color.DarkSeaGreen (version: 1.0.0-beta0007) 

### ISSUE THREAD

**Issue by zappyzhao** [SixLabors/ImageSharp#1015]
In Rgba color definition, DarkSeaGreen has the hex value of "#8FBC8B". And based on the summary it should match the W3C definition.

However in W3C definition it's actually #8FBC8F: https://www.w3.org/wiki/CSS3/Color/Extended_color_keywords

This didn't happen in the previous versions I believe, is this a bug?

**Comment by dlemstra** [comment]
It looks like the colors are based on the values that are used in `System.Drawing.Color`. And it looks like you found a bug in System.Drawing also. In the code `0xFF8FBC8B` is used: https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Drawing/KnownColorTable.cs#L48. But the comments say is should be `#FF8FBC8F`: https://docs.microsoft.com/en-us/dotnet/api/system.drawing.color.darkseagreen?view=netframework-4.8. Feel free to open a PR to resolve this.

**Comment by adrianknight89** [comment]
@dlemstra I'm having another issue with colors. I call

`DrawText(this IImageProcessingContext source, TextGraphicsOptions options, string text, Font font, Color color, PointF location);`

extension method to draw a white letter. This used to work, but when I updated my packages, the letter is no longer drawn in white. It looks pink. I used to pass `Rgba32.White`. I changed it to `Color.White`, and the issue was fixed.

**Comment by antonfirsov** [comment]
@adrianknight89 can you do us a favor and open a new issue for this, having the template filled + providing a minimalistoc repro?

**Comment by adrianknight89** [comment]
@antonfirsov I tried to reproduce this issue outside of my application without luck. If I can reproduce it, I'll open a ticket. Thanks.

**Comment by zappyzhao** [comment]
Also making a PR for updating in System.Drawing.Common: https://github.com/dotnet/corefx/pull/41561
