### ISSUE TITLE
unable to process .jxr, .webP, .jpg extension images in SixLabours  Version 1.0.0-beta0007 in .NET Core 

### ISSUE THREAD

**Issue by jayrajmishra** [SixLabors/ImageSharp#1101]
Unable to process .jxr, .webP, .jpg images using SixLabors.ImageSharp pulgin - Version 1.0.0-beta0007. It throws error. Is there any solution to fix the issue beside GIF,PNG,JPEG,BMP format images.

Error Message : 

Image cannot be loaded. Available decoders:

GIF : GifDecoder
PNG : PngDecoder
JPEG : JpegDecoder
BMP : BmpDecoder

**Comment by antonfirsov** [comment]
@jayrajmishra you mentioned 3 different formats/file extensions:
- **.jpg**is another extension is for format JPEG it should work. Do you have issues opening a specific jpeg file? If you can you provide a working repro (image+code) for that, please free to open another issue with that information provided & **template filled in**. If you have questions, we can help in our [gitter channel](https://gitter.im/ImageSharp/General).
- ***webP**: we already have an open issue for that, work is in progress: #121 
- **.jxr**: this looks like a feature request ---> should be discussed [in gitter](https://gitter.im/ImageSharp/General) before opening an issue (see [contribution guide](https://github.com/SixLabors/ImageSharp/blob/master/.github/CONTRIBUTING.md#do-you-intend-to-add-a-new-feature-or-change-an-existing-one)). The reason is that we need more information from users to understand and prioritize it (specific use case, how critical it is etc.)

**Comment by JimBobSquarePants** [comment]
Asked also on Stack Overflow.

https://stackoverflow.com/questions/59751572/unable-to-process-jpg-images-using-sixlabors-imagesharp-in-c-sharp-version-1/59771703?noredirect=1#comment106075468_59771703

**Comment by jayrajmishra** [comment]
I am unable to get the proper solution of this issue, unable to process the .jpg image.

**Comment by JimBobSquarePants** [comment]
You need to provide the image. It's impossible for us to help you without it.

**Comment by jayrajmishra** [comment]
This two images are not been processed with SixLabours pulgin in .NET Core
**.jpgImage** - https://www.dropbox.com/s/2218dray4uwwm2r/Image1.jpg?raw=1
**.jxr Image** - https://www.dropbox.com/s/0p60vqz1sox0gms/Image2.jxr?raw=1

**Comment by JimBobSquarePants** [comment]
@jayrajmishra 

I was able to open the **.jpg** image without issue with the **1.0.0-beta0007**

Here is your image, loaded and altered to have it's edges detected by our edge detection method.

![1101](https://user-images.githubusercontent.com/385879/73591302-0f4b3800-4541-11ea-951a-8619b81f75f7.jpg)

So if you are having issues, they are occurring, elsewhere in your codebase and have nothing to do with the library. As long as you provide the jpeg data intact then we can decode it.

As mentioned before and described by the error message. **.jxr** images are not a supported format. You will need to discuss the feature request in our Gitter channel. 

>**.jxr**: this looks like a feature request ---> should be discussed [in gitter](https://gitter.im/ImageSharp/General) before opening an issue (see [contribution guide](https://github.com/SixLabors/ImageSharp/blob/master/.github/CONTRIBUTING.md#do-you-intend-to-add-a-new-feature-or-change-an-existing-one)). The reason is that we need more information from users to understand and prioritize it (specific use case, how critical it is etc.)

Please be aware that it is absolutely critical that you follow our rules when raising issues and use the provided templates.

As I have demonstrated there is the library can open your image I am keeping this issue closed.

**Comment by jayrajmishra** [comment]
Ok, Is the Feature has been developed for .jxr, .webP file Image. @JimBobSquarePants

**Comment by jayrajmishra** [comment]
.**webP**  file is not been process in SixLabours 

URL : https://www.dropbox.com/s/3ui7hxdrczcjw5i/4-color-2.webp?raw=1

Error Message: Image cannot be loaded. Available decoders:
 - BMP : BmpDecoder
 - JPEG : JpegDecoder
 - GIF : GifDecoder
 - PNG : PngDecoder

   at SixLabors.ImageSharp.Image.Load(Configuration config, Stream stream, IImageFormat& format)

Now does SixLabors support .jxr file?

**Comment by JimBobSquarePants** [comment]
@jayrajmishra Can you please stop spamming this issue tracker. We have told you on several occasion that those formats are not supported. If you continue to spam closed issues you will be banned.
