### ISSUE TITLE
Add Color.FromHtml

### ISSUE THREAD

**Issue by HarelM** [SixLabors/ImageSharp#1103]
It would be extremely useful for migration from `System.Drawing` to this library to have the `FromHtml` equivalent.
The `FromHtml` takes a string which can be a color name or hex string and converts it to the relevant color.
As a side note, there are 3.5 million downloads to this library, I think it can be released instead of being a pre-release...
Can also be called `Color.FromString`.

**Comment by JimBobSquarePants** [comment]
> As a side note, there are 3.5 million downloads to this library, I think it can be released instead of being a pre-release

Nearly there. Got a few API updates to make and we'll be ready for the RC1 release. You'd be amazed how much churn there has actually been getting this correct.

**Comment by JimBobSquarePants** [comment]
@HarelM I've added two new methods to the API, you can grab them from the nightlies now.

`void Color.Parse(string input)` and `bool Color.TryParse(string input, out Color result)`

**Comment by HarelM** [comment]
Cool! Thanks for the quick implementation!
Let me know when a new version is released.

**Comment by JimBobSquarePants** [comment]
There's a download available right now from our MyGet feed. It's very close to what our RC1 build will be so I recommend it.

**Comment by HarelM** [comment]
Any chance for a pre-release on global Nuget? I prefer not to add MyGet source to my build CI machine/code if possible :-)

**Comment by antonfirsov** [comment]
Personally, I understand your concern (a few weeks ago we lost the whole history by mistake :disappointed:  ), put publishing to nuget is a big chore. Having proper release notes is an absolute minimum to do, and it's already a lot of work.

The more frequently we do this, the less time we have to do actual features and bugfixes, so we prefer to stick to our milestones, unless we miss the original deadline by months. Beta6 and 7 were released because of this, we'd like to avoid having a Beta8.
