### ISSUE TITLE
Introduce PixelTypeInfo.HasAlpha

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1396]
## Motivation

By introducing a property to observe whether a given pixel type has an alpha, we can then use it in our processors to omit unnecessary alpha premultiplication. Might be also interesting for users working with `Image.Identify`.

We need to make sure it's value is properly filled:
- In decoders with `Identify` implementations  (PNG, BMP)
- For all built-in pixel formats (`IPixel`-s)

## API alternatives

In https://github.com/SixLabors/ImageSharp/discussions/1394#discussioncomment-106875 I forgot that extending `IPixel` is actually a breaking change.  Non-breaking variant:

```C#
internal enum PixelAlphaRepresentation
{
    None,
    Associated,
    Unassociated
}

public class PixelTypeInfo
{
     // 'null' means unknown/not implemented
     public PixelAlphaRepresentation? AlphaRepresentation { get; }    
}

public PixelOperations<TPixel>
{
     // Return AlphaRepresentation == null by default, but for important pixel types, introduce proper overrides with T4:
     public virtual PixelTypeInfo GetPixelTypeInfo();
}
```

**Comment by JimBobSquarePants** [comment]
I can see us adding `ChannelCount` to this type at some point so I guess that would be nullable also.

**Comment by antonfirsov** [comment]
@JimBobSquarePants so you prefer the non-breaking variant? Honestly, now it looks like a safer way to go to me.
Also allows us to extend codecs incrementally to detect `PixelTypeInfo` details.

**Comment by JimBobSquarePants** [comment]
Yeah, it's a safe clever approach. Big fan!

**Comment by saucecontrol** [comment]
I might be misreading the purpose of this, but did you consider support for pixel formats that are already premultiplied?  [TIFF](https://www.awaresystems.be/imaging/tiff/tifftags/extrasamples.html) and [DirectX](https://docs.microsoft.com/en-us/windows/win32/api/dcommon/ne-dcommon-d2d1_alpha_mode) (among others) support alpha in both forms.

I recall we had a chat about this somewhere, although I've since lost track of it... I set up a generic pixel format descriptor type [here](https://github.com/saucecontrol/PhotoSauce/blob/master/src/MagicScaler/Core/PixelFormats.cs) which borrows heavily from WIC's pluggable pixel format model and describes alpha using an enum if you're looking for inspiration.

**Comment by JimBobSquarePants** [comment]
Oh I remember this stuff yeah, will definitely have to use it as a source of inspiration!

**Comment by antonfirsov** [comment]
@saucecontrol do I get this right?
- `None`: has no alpha
- `Associated`: has alpha, pixel is premultiplied
- `Unassociated`: has alpha,  pixel is not premultiplied

@JimBobSquarePants edited my proposal, let's go with the non-breaking version + enum for `PixelAlphaRepresentation`.

**Comment by saucecontrol** [comment]
Yep, that's right.  DirectX uses `Ignore`, `Premultiplied`, and `Straight` to describe those values.  I'm not sure which is more intuitive.

**Comment by JimBobSquarePants** [comment]
I much prefer your naming.

**Comment by JimBobSquarePants** [comment]
I've started this.
