### ISSUE TITLE
Square artifacts in color data on jpeg outputs

### ISSUE THREAD

**Issue by jrdiver** [SixLabors/ImageSharp#1545]
I was messing with the Resize sample just trying to figure out the library, but I keep getting some weird 
block artifacts when the quality is set to less then a jpg quality of 91 on ImageSharp's NuGet package 1.0.3-Alpha.0.35

I reverted it back to the latest stable - 1.0.2 and the issue went away.  Code used is basicly the sample besides removing grayscale and changing output to jpg with a quality setting.

`
           System.IO.Directory.CreateDirectory("output");

            using (Image image = Image.Load("fb.jpg"))
            {
                image.Mutate(x => x.Resize(image.Width / 2, image.Height / 2));

            image.SaveAsJpeg("output/Photo.jpg", new JpegEncoder { Quality = 75 }); // Automatic encoder selected based on extension.
            }
`

### System Configuration
Windows 10/Visual Studio 2019/NetCore3.1

![fb](https://user-images.githubusercontent.com/12983591/107839316-9fd17080-6d70-11eb-9ea6-1620e0f2f986.jpg)
![Photo](https://user-images.githubusercontent.com/12983591/107839317-a1029d80-6d70-11eb-9d30-26e2d153fe38.jpg)

**Comment by JimBobSquarePants** [comment]
@jrdiver This would have been better raised as a discussion. Please in future use the supplied template. It's very important that you do so. 

Please, with all the required information, also supply comparison output images so that we do not have to spend time replicating your process before we can even determine whether there is an issue.
