### ISSUE TITLE
Some components do not check the return value of Stream.Read

### ISSUE THREAD

**Issue by chausner** [SixLabors/ImageSharp#186]
I noticed that in many locations where data is read from a Stream the return value (number of bytes read) of Stream.Read is not checked. This is bad because of two reasons:
- It is assumed that there is always enough data in the stream to read the full buffer which may not always be the case (e.g. when files are corrupted/truncated). If you do not check how many bytes were actually read you cannot detect when an unexpected end of a stream has been reached.
- According to documentation, Stream implementations are free to read less than the number of requested bytes. While I think this case does not happen in practice with typical FileStream implementations, it is very common for NetworkStreams, for example. In any case, it should be treated as an implementation detail and not relied upon. The correct way to read a certain number of bytes from a stream is to use BinaryReader.Read or BinaryReader.ReadBytes. These methods are guaranteed to return less data only if the end of the stream has been reached.

**Comment by blackcity** [comment]
In general I agree with you. Regarding network streams the library already takes care. A network stream is not seekable and because the library needs a seekable stream it copies the stream to a MemoryStream.. This operation ensures that the stream fully transmitted. But maybe this should be an async operation in order to not block the thread.
https://github.com/JimBobSquarePants/ImageSharp/blob/master/src/ImageSharp/Image.FromStream.cs#L225
So I do not think this is currently a big problem but it might be handled.

This said, I consider it as bad practice for the calling code to rely on the library to handle network streams correctly. The calling code is clearly responsible here.

**Comment by JimBobSquarePants** [comment]
I'm closing this. As @blackcity correctly states, it's not our responsibility to handle network streams. 
No other graphics library would be expected to either. 

We only copy to a MemoryStream if the given stream is not seekable so I wouldn't be inclined to make this async internally. Nothing to stop calling code from being async though.

**Comment by chausner** [comment]
I remain convinced that the current way how components read from streams is incorrect and should be avoided. While it may "work in practice" in 99% of all cases, it is still wrong. I am not sure if any changes have been made since I reported this issue but last time I checked, ImageSharp would not recognize invalid, truncated images, for example, due to exactly that issue.

**Comment by chausner** [comment]
Instead of internally copying non-seekable streams to a MemoryStream, why not simply throw an exception when CanSeek is false? Let the API caller be responsible for passing a seekable stream to ImageSharp. If the caller has a non-seekable stream, they can decide themselves whether to copy synchronously or asynchronously to a MemoryStream first.

**Comment by JimBobSquarePants** [comment]
Hi @chausner

> I am not sure if any changes have been made since I reported this issue but last time I checked, ImageSharp would not recognize invalid, truncated images, for example, due to exactly that issue.

I'm afraid you thought exactly wrong. ImageSharp failed to read some images incorrectly because it was failing to recover from invalid data or missing data within poorly encoded or corrupt images. I actually fixed an issue within the png decoder to better handle that [yesterday](https://github.com/SixLabors/ImageSharp/pull/359/files#diff-b4f626cf509fdbafd46cc45da8aed941R1127). We've also done work elsewhere to ensure that we respect hitting the ends of streams correctly.  Everything else is safely behind our decoder sanitation code.

I don't know what experience you have had writing image decoders but they all work to the same pattern of identifying specific markers within the image and processing those markers. All but a few issues are due to mistakes made in other encoders. 

We can now successfully decode many corrupt images and include them in our [test suite](https://github.com/SixLabors/ImageSharp/tree/8b2b7c780821a18db351e796ce41178c9ce95e95/tests/Images/Input/Jpg/issues).

>The idea of the abstract Stream class is to allow APIs to support reading from arbitrary types of data sources, whether the data comes from a file, memory or the network.

I know what they are for. We handle both file and memory streams. We do not handle chunked network streams and require that stream to be completely populated before passing the the image. That's perfectly reasonable in my opinion.

>Instead of internally copying non-seekable streams to a MemoryStream, why not simply throw an exception when CanSeek is false?

Because it makes life a lot easier for me. It's very rare that someone will pass a non-seekable stream to the library but when they do it's much quicker and easier for me to simply transparently handle that situation than to walk someone through why their code is failing. It's almost always someone with very limited experience that would require an entire course on streams before they'd understand what was happening. 

Hope that clarifies things

Cheers

James
