### ISSUE TITLE
Basic memory diagnostics

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1883]
Spinning off https://github.com/SixLabors/ImageSharp/issues/1739#issuecomment-984667382 to an issue.

We need expose some basic memory diagnostic utilities from library code:

```C#
namespace SixLabors.ImageSharp.Diagnostics
{
    public static class MemoryTracker
    {
        // Count outstanding MemoryAllocator allocations. Dispose reduces the counter, finalizer doesn't.
        public static long TotalUndisposedLogicalAllocationCount { get; }

        // Make the library throw in finalizers if stuff was left undisposed
        public static bool EnableStrictDisposeWatcher { get; set; }
    }
}
````

We should also introduce standard [event counters](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/event-counters), but that's a different story for a separate issue later.

**Comment by gfoidl** [comment]
Instead of individual static properties for "memory info" there should be only static method, that in turn return a type which represents the memory info.
```c#
namespace SixLabors.ImageSharp.Diagnostics
{
    public static class MemoryTracker
    {
        public static MemoryInfo GetMemoryInfo();

        // Make the library throw in finalizers if stuff was left undisposed
        public static bool EnableStrictDisposeWatcher { get; set; }
    }

    // or a normal struct, here just for simplicity
    public readonly record struct MemoryInfo(long TotalUndisposedLogicalAllocationCount);
}
```
That way it's easier extend the memory info and/or get the "info at once" without the need to query several properties (in the assumption that there will be more properties for memory info in the future).

This should be the first point to start with.
Based on top of that, event counters (respectively an event source that provides counters) can be created.

--- 

Personally I'm quite busy now, so I don't feel able to do the first step. But (later) for the event counters I'm sure to help out (use these in my work project quite extensively, so some good patterns evolved for implementing).

**Comment by antonfirsov** [comment]
@gfoidl great idea thanks!

> But (later) for the event counters I'm sure to help out

We would definitely appreciate help!

**Comment by antonfirsov** [comment]
In general, telemetry is something that would be great to see being introduced in the library, but we are struggling to find time for it.

**Comment by antonfirsov** [comment]
While documenting the implementation I realized I'm not sure about the `MemoryInfo` variant anymore. This is not GC, I don't see us having nearly as many statistics as `GCMemoryInfo`, at least not valuable ones.

A single static property is much easier to discover. I prefer whatever helps the user more at this point.
