### ISSUE TITLE
Question about migration from ImageProcessor to ImageSharp

### ISSUE THREAD

**Issue by ahamana** [SixLabors/ImageSharp#1908]
I will migrate ImageProcessor to ImageSharp.

Does ImageSharp have an alternative method of `ImageProcessor.ImageFactory.Gamma(float value)`?

**Comment by JimBobSquarePants** [comment]
See https://stackoverflow.com/a/62766295/427899

**Comment by murerfel** [comment]
Unfortunately, I cannot add a comment on the StackOverflow, so I'll do it here.

While I see that setting a gamma value might be a simple operation for someone very familiar with the subject, it is a big pain point for someone like me, who is just migrating from `ImageProcessor` and loses the ability in the API to set the gamma. 
If it's such a simple operation, it probably wouldn't be much effort to add it to the `IImageProcessingContext` ? 

The way it is now, instead of just porting the API, I need to figure out what the exact transformation function, how I can iterate manually over pixels and apply that function. IMHO, that's exactly the kind of operation an API should offer.
