### ISSUE TITLE
Some old jpg images are saved with glitches (regression in alpha)

### ISSUE THREAD

**Issue by botinko** [SixLabors/ImageSharp#1978]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Some pictures of our clients get corrupted when resizing and even when simply resaving by ImageSharp. 
Issue exists in `2.0.0-alpha.0.168` but doesn't exists in `v1.0.4`. 

### Steps to Reproduce
```
            var img = Image.Load(@"issue.jpg");
            img.Save("copy.jpg");
```
before
![issue](https://user-images.githubusercontent.com/2981998/152630871-cb8c08c5-17b9-43e9-852c-44a5ed11d56e.jpg)
after
![copy](https://user-images.githubusercontent.com/2981998/152630935-2706ff5f-dfd5-4a33-92d6-641a167857c7.jpg)

Link to original image and image after resaving https://drive.google.com/file/d/1_k54RFuPciKeKBtFDLftIKetOPsWkOFO/view?usp=sharing

If you resave the image in any editor, the problem stops reproducing. So you need an original image from archive to reproduce. 

### System Configuration
- Other ImageSharp packages and versions: 2.0.0-alpha.0.168
- Environment (Operating system, version and so on): Windows 10, docker
- .NET Framework version: dotnet 5, 6
- Additional information: issue doesn't exists in v1.0.4.

**Comment by br3aker** [comment]
Can confirm on my machine. Will work on it asap.

**Comment by br3aker** [comment]
I've found error leading to this. It was broken in https://github.com/SixLabors/ImageSharp/pull/1694 which did spectral -> color conversion withing spectral strides instead of full image.

Everything does work in current tests because we don't have a single component jpeg with non 1x1 sampling factors in current test suite. ITU spec says that any single component jpeg must be decoded as 'non-interleaved' jpeg:

> When Ns = 1 (where Ns is the number of components in a scan), the order of data units within a scan shall be left-to-right
and top-to-bottom, as shown in Figure A.2. This ordering applies whenever Ns = 1, regardless of the values of
H1 and V1.
![image](https://user-images.githubusercontent.com/20967409/152642463-6fb6a30c-5f18-4f86-a3c4-d1158cd166fc.png)

Current decoder implementation decodes single-component jpegs int interleaved mode and it works for 1x1/2x1/4x1  sampling jpegs but vertical sampling factors breaks it due to interleaved 'traversal':
![image](https://user-images.githubusercontent.com/20967409/152642458-f9e2bd9c-9626-4949-9959-8a7c91e0cf81.png)

Fix should be fairly simple, will try to create a PR today.

P.S.
@botinko can we include your example image in out test suite? It would help a lot as we don't have such exotic image right now :)

**Comment by botinko** [comment]
@br3aker Thank you very much for such a quick response! Sure, you can use it for your tests.

**Comment by br3aker** [comment]
@botinko thanks! Fix is ready and should be available in the nearest nightly build after merge, thanks for pointing this one :)
