### ISSUE TITLE
Namespace "SixLabors.ImageSharp" does not match folder structure. Expected "SixLabors.ImageSharp.Primitives".

### ISSUE THREAD

**Issue by ujk13** [SixLabors/ImageSharp#2096]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.0

### Other ImageSharp packages and versions

2.0.0

### Environment (Operating system, version and so on)

Windows 10 Enterprise

### .NET Framework version

6.0

### Description

Using SixLabors.ImageSharp nugget for a long time now, and been through different versions. Last two updates, we have this error when we cannot access some structs and classes under the folder Primitives, because it is not structured properly the namespace.
![image](https://user-images.githubusercontent.com/103740510/164177717-f9796401-fcac-445f-85b0-4ffedd4ecf3a.png)

### Steps to Reproduce

Go to the code, open a file under the folder Primitives, some of them don't have the proper namespace structure so to access them.

**Comment by JimBobSquarePants** [comment]
I’m not sure what you are trying to do.

The Primatives namespace has not been in use since early pre V1 betas and the API is documented.

If you are trying to build from source and are unable to do so due to namespace warnings this is because you have not followed the explicit instructions as dictated in the readme.

Either way this tracker should be used for issues only and as such I have closed this as invalid.
