### ISSUE TITLE
net core 6 rending issue of Barcode

### ISSUE THREAD

**Issue by Alik2015** [SixLabors/ImageSharp#2118]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

latest

### Other ImageSharp packages and versions

none

### Environment (Operating system, version and so on)

windows/linus

### .NET Framework version

6.0

### Description

Asked this question and described issue here.

https://stackoverflow.com/questions/72209275/replacing-system-drawing-with-imagesharp-for-barcode-net-core-6?noredirect=1#comment127586447_72209275

It was also suggested by a user on comments to create issue as they also tried the same thing.

### Steps to Reproduce

https://stackoverflow.com/questions/72209275/replacing-system-drawing-with-imagesharp-for-barcode-net-core-6?noredirect=1#comment127586447_72209275

**Comment by tocsoft** [comment]
@Alik2015 this is most likely an issue on the https://github.com/micjahn/ZXing.Net/ end of things you should probably be raising an issue over there as we don't own ZXing,Net .

If it turns out to be an issue with ImageSharp itself I would expect the ZXing devs to raise an issue/PR to fix the issue so i'm closing this until its been looked at on the ZXing side first.

PS. when you raise issues on OSS projects you generally want to fill in all the details of the issue directly on their issue tracker rather than just linking to something you have posted elsewhere... most OSS maintainers are doing this for free on our own time so you can't expect them to have to to figure out what the actual issue is.

**Comment by Alik2015** [comment]
Appreciate the suggestion and fixed by actually putting testable code.  I do believe the issue is with ImageSharp as it is responsible for the rendering and as you can tell from my code if Ssystem.Drawing is used all is well.
