### ISSUE TITLE
Loading a GIF results in a bigger file

### ISSUE THREAD

**Issue by sescandell** [SixLabors/ImageSharp#2198]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

None, made a simple monofile sample repo in .Net6

### Environment (Operating system, version and so on)

Windows 11, .Net6 (but not limited to this framework)

### .NET Framework version

.Net4.8, netcore3.1, net6

### Description

Hi,

I made a dummy test: load a GIF file, then save it somewhere else without processing it. The final file has a bigger size than the original (more than twice its size, but variable depending on the source. I observed a 5x on another image).

Am I missing an option on save?

Thanks,

### Steps to Reproduce

Here is a fully sample working test (.Net6, dependency : Image.Sharp v.2.1.3)

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="sample.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

```csharp
// program.cs
using SixLabors.ImageSharp;

Console.WriteLine("Cloning...");

Directory.CreateDirectory("results");
using var src = File.OpenRead("sample.gif");
File.Delete("results/output.gif");
using var fs = File.OpenWrite("results/output.gif");

using var image = await Image.LoadAsync(src);
await image.SaveAsGifAsync(fs);

await fs.FlushAsync();

Console.WriteLine("Done");
Console.WriteLine($"SrcSize: {src.Length / 1024}");
Console.WriteLine($"OutputSize: {fs.Length / 1024}");
Console.ReadKey();
```

Results sample:

> Cloning...
> Done
> SrcSize: 1819
> OutputSize: 3886

### Images

I'm using a zip folder to be sure Github doesn't transform the file himself,
[sample.zip](https://github.com/SixLabors/ImageSharp/files/9261769/sample.zip)

**Comment by sescandell** [comment]
Hi @JimBobSquarePants 

It's a mix of random GIFs from Giphy for example and some made with the tool [Canva](https://www.canva.com/fr_fr/creer/gif-maker/)

**Comment by JimBobSquarePants** [comment]
Thanks. I'll have a dig into our LZW encoder

**Comment by brianpopow** [comment]
This is only a guess, but maybe the issue is not the LZW encoder and rather the how the quantization is done? I have checked the provided test image. It has only 253 color. Maybe in those cases (< 256 colors), we should not quantize the image again and go with the colors the image has.

**Comment by JimBobSquarePants** [comment]
Interesting… I thought both palettes were full. 

I can do a test by encoding using the input palette to confirm

**Comment by JimBobSquarePants** [comment]
Looks like there is an issue with compression.

I'm using a cool little app called [gifiddle](https://github.com/ata4/gifiddle) to compare the output having hacked our code to always preserve the global palette.

As you can see from the metrics the palette is the same, but we are failing to compress it as well as the input.

<img alt="image" src="https://user-images.githubusercontent.com/385879/192175455-2d301a68-fdad-4181-a2f4-35ac35e16044.png">

Our lookups appear to be matching also as the frames color appears to match exactly.

<img alt="image" src="https://user-images.githubusercontent.com/385879/192175772-1a6771b6-1f56-4554-aa54-fe08f777dc61.png">

**Comment by JimBobSquarePants** [comment]
I rewrote the LzwEncoder based on https://github.com/deanm/omggif and was able to make a couple of very minor savings (62 bytes) due to the fact that we max out our subblock sizes at 254 instead of 255 bytes. I may actually switch it out because it's about half the code of our existing implementation.

However, that doesn't actually begin to touch the difference. I can only surmise that it must be getting encoded using some dark magic like [Lossly LZW](https://kornel.ski/lossygif)

I'm not sure we can actually do anything about the difference now.

**Comment by JimBobSquarePants** [comment]
I had another look at this using https://ezgif.com/ to experiment. The original is definitely using lossy encoding. It's the only way to make those saving.

**Comment by JimBobSquarePants** [comment]
We were chasing a red herring with the lossy encoding. When splitting the gif frames I was including the data from previous frames so couldn't see the obvious.

The gif in question is heavily optimized by the allpication of a de-duplication algorithm which strips out duplicate indexing detail from a frame by including only the changes between frames. This can lead to really good compression since you now have larger areas of equal values.

With the changes introduced in #2455 we go a very long way to improve the output size by introducing our own deduplicating algorithm and dropping 1.6MB off our encoded size.

Now... We don't end up with a result that exactly matches because we have to cater for images using millions of colors so use a memory (_and accuracy_) limited lookup table to match colors using a palette quantizer so mileage may vary, but we are capable of beating previously optimized efforts. The image in #2450 for example will be encoded with a saving of 0.37MB when compared to the original.

You can see a comparion of encoded frames in this image.

Left original, right ImageSharp.

<img  alt="image" src="https://github.com/SixLabors/ImageSharp/assets/385879/09e810b1-446f-45c1-875c-8386b609aa6b">
