### ISSUE TITLE
GrayScale Image with high dynamic range being treated as binary

### ISSUE THREAD

**Issue by jmilbrandt2** [SixLabors/ImageSharp#2242]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

All

### Other ImageSharp packages and versions

All

### Environment (Operating system, version and so on)

Windows

### .NET Framework version

.NET Standard 2.0

### Description

 byte[] data1 = File.ReadAllBytes("fileinquestion");
   SixLabors.ImageSharp.Image img = SixLabors.ImageSharp.Image.Load(data1, decoder);

### Steps to Reproduce

very easy just load the image and you will see it is not treated as grayscale even though in Photoshop and in Java Library ImageJ it is clearly GrayScale

### Images

https://stackoverflow.com/questions/73860945/image-not-viewable-using-c-sharp-libraries-viewable-in-imagej-or-imagej-online-h/73861281?noredirect=1#comment130421416_73861281

https://drive.google.com/file/d/16Xotc-2CJ6HkEJDysfKBkjClkU1OGiyQ/view?usp=sharing
![OU7YE](https://user-images.githubusercontent.com/96636922/192416279-3faa712a-7d16-46c0-8dba-1572a126bf93.png)

**Comment by jmilbrandt2** [comment]
this image is in Tiff format

**Comment by JimBobSquarePants** [comment]
By default, the TiffDecoder will decode images as `Rgba32` when using the non-generic API, (_something we can look into updating for v3 based upon the bit depth_), so you will not be capturing the image information since you are squashing 16bpp info into 8bpp.

Currently you can use `Image.Identify(...)` to determine the correct bit depth and make intelligent decoding choices, however, given that you know this image is grayscale and has a high dynamic range let's just decode it using `L16` (_16bit single luminance component_) and then stretch the histogram using the newly added method for V3. https://github.com/SixLabors/ImageSharp/pull/2235

``` c#
using Image<La16> image = Image.Load<La16>(...);
image.Mutate(x => x.HistogramEqualization(new()
{
    LuminanceLevels = 65536,
    Method = HistogramEqualizationMethod.AutoLevel
}));
image.SaveAsPng(...)
```

The result is as expected. 

![DecodeMystery_L16_mystery](https://user-images.githubusercontent.com/385879/192429613-46231aad-f7d3-459b-bf22-f1689d4419b9.png)
