### ISSUE TITLE
Unexpected artefacts when quantizing images

### ISSUE THREAD

**Issue by BrentCoxEscentual** [SixLabors/ImageSharp#2469]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

NA

### Environment (Operating system, version and so on)

Windows, Linux

### .NET Framework version

6

### Description

We are currently experiencing strange artifacts when quantizing images.

### Steps to Reproduce

Load image.
Quantize the image using KnownQuantizers.Wu
The saved output will have unexpected artifacts.

Below is a test program I created to replicate the problem. It does not happen on all images only on some. I have attached a image that it happens on. If you compare the original to the quantized version you will note a grey triangular artifact from right of centre to the right middle of the image.

```
using SixLabors.ImageSharp.Formats.Png;

using (var i = Image.Load("Orig.png"))
{
    i.Mutate(x => x.Quantize(KnownQuantizers.Wu));
    await i.SaveAsPngAsync("Resized.png", new PngEncoder()
    {
        CompressionLevel = PngCompressionLevel.BestCompression,
    });
}
```
Original Image
![Orig](https://github.com/SixLabors/ImageSharp/assets/68946782/146f7835-7d6a-47d0-90fe-08b3581cba63)
Quantized Image
![Resized](https://github.com/SixLabors/ImageSharp/assets/68946782/d0954b4d-4a05-433f-a6e2-a25af274cdf0)

### Images

![Orig](https://github.com/SixLabors/ImageSharp/assets/68946782/3d6190fb-d6bc-4425-b56f-8feae43c84f0)
![Resized](https://github.com/SixLabors/ImageSharp/assets/68946782/eccdc030-c970-4027-bc5f-97f3b0a67b4c)

**Comment by James-Jackson-South** [comment]
What happens when you quantize without dithering? 

Why are you quantizing then resaving at 32bit?

**Comment by JimBobSquarePants** [comment]
What happens when you quantize without dithering?

Why are you quantizing then resaving at 32bit?

**Comment by BrentCoxEscentual** [comment]
> 

Hi there,

I created the the demo program with the absolute minimum code to illustrate the problem that I came across while working with the library and thought it best to raise it.

As to saving as 32 bit, it was not a conscious decision.

I am happy to try with out dithering with you could point me in the right direction how I can do that.

Thanks for your time with this

**Comment by JimBobSquarePants** [comment]
>I am happy to try with out dithering with you could point me in the right direction how I can do that.

Instead of using `KnownQuantizers.Wu` new up an instance of the [WuQuantizer](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Processing.Processors.Quantization.WuQuantizer.html#constructors) and passing [QuantizerOptions.Dither](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Processing.Processors.Quantization.QuantizerOptions.html#SixLabors_ImageSharp_Processing_Processors_Quantization_QuantizerOptions_Dither) as null. 

It's likely the dither as the pattern stems down and left from the widening as it does which is the direction error diffusion goes.

You can set the [strength of the dither (0-1)](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Processing.Processors.Quantization.QuantizerOptions.html#SixLabors_ImageSharp_Processing_Processors_Quantization_QuantizerOptions_DitherScale) in those same options.

**Comment by BrentCoxEscentual** [comment]
> > I am happy to try with out dithering with you could point me in the right direction how I can do that.
> 
> Instead of using `KnownQuantizers.Wu` new up an instance of the [WuQuantizer](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Processing.Processors.Quantization.WuQuantizer.html#constructors) and passing [QuantizerOptions.Dither](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Processing.Processors.Quantization.QuantizerOptions.html#SixLabors_ImageSharp_Processing_Processors_Quantization_QuantizerOptions_Dither) as null.
> 
> It's likely the dither as the pattern stems down and left from the widening as it does which is the direction error diffusion goes.
> 
> You can set the [strength of the dither (0-1)](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Processing.Processors.Quantization.QuantizerOptions.html#SixLabors_ImageSharp_Processing_Processors_Quantization_QuantizerOptions_DitherScale) in those same options.

Hi there

I have made the change as suggested.

```
using (var i = Image.Load("Orig.png"))
{
    i.Mutate(x => x.Quantize(new WuQuantizer(new QuantizerOptions()
    {
        Dither = null
    })));

    await i.SaveAsPngAsync("test.png", new PngEncoder()
    {
        CompressionLevel = PngCompressionLevel.BestCompression
    });
}
```

The artifact has now disappeared and the image is as expect. Purely for my education and better understanding, why do you think the dithering would cause this issue?

Thanks again for you time and help.

Regards

**Comment by JimBobSquarePants** [comment]
The dithering algorithms work by pushing error (this difference between a quantized pixel and the original) to its surrounding pixels.

For example, Floyd Steinburg propagates the error to the neighboring pixels as follows:

- Distribute 7/16 of the error to the pixel on the right.
- Distribute 3/16 of the error to the pixel on the bottom-left.
- Distribute 5/16 of the error to the pixel directly below.
- Distribute 1/16 of the error to the pixel on the bottom-right.

We use a lookup table that stores up to 5 bits of pixel data per component to match the result of a quantized pixel against it's undithered equivalent. We use 5 bits as that keeps memory low (6 bits would be preferred but that uses over 30 MB compared to 2 1/4 MB). Sometimes we end up with a collision which leads to the artifacts you are seeing.

This, in the case of your image pushes the artifact caused by that shadow down and to the right. This is why I suggested adjusting the strength of the dithering. Using .5F as a parameter for example would reduce the error by half.

Here's the output from doing that.

![Issue2469_Quantized_Encode_Artifacts_Rgba32_issue_2469](https://github.com/SixLabors/ImageSharp/assets/385879/702896df-db89-44a1-87d1-fb46e4c5969f)

**Comment by JimBobSquarePants** [comment]
I've actually opened up #2473 which allocates more memory towards alpha component comparisons in our lookup table which fixes the issue using the default encoder settings.
