### ISSUE TITLE
Error SixLabors.ImageSharp.ImageFormatException: 'Unexpected chunk followed VP8X header'

### ISSUE THREAD

**Issue by chienits** [SixLabors/ImageSharp#2695]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.7

### Other ImageSharp packages and versions

2.1.7

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

4.7.2

### Description

Unable Load webp image

### Steps to Reproduce

I'm using Net framework 4.7.2

**Comment by JimBobSquarePants** [comment]
It's so disappointing to see issues like this opened. 

![image](https://github.com/SixLabors/ImageSharp/assets/385879/0852955e-f683-490e-8b52-c303fb71a84a)

These questions should be filled correctly in or otherwise you are completely wasting my time! The latest version of ImageSharp as of this time is [v3.1.3](https://www.nuget.org/packages/SixLabors.ImageSharp/3.1.3) a full major version over the one you are raising an issue for.

**Comment by chienits** [comment]
**I'm using .NET Framework (only latest v2.1.7 supported)**
ImageSharp v3.1.3 only support Netcore

**Comment by JimBobSquarePants** [comment]
And you think I should support outdated versions of Open-Source code?
