### ISSUE TITLE
regression on latest.. 3 vs 2 with GIF

### ISSUE THREAD

**Issue by Seabizkit** [SixLabors/ImageSharp#2700]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

latest 3.x

### Other ImageSharp packages and versions

3

### Environment (Operating system, version and so on)

Windows 

### .NET Framework version

.net core 8

### Description

resizing make artifacts in 3 which it does not in 2

### Steps to Reproduce

resize the gif

### Images

![lovebear](https://github.com/SixLabors/ImageSharp/assets/1920090/8e596b4e-8867-4aab-b2c4-9a0fc99321ef)

resize this image with 3 vs 2 and look at the eyes

**Comment by JimBobSquarePants** [comment]
This isn't good enough. You need to actually produce the expected vs actual output and provide code samples.

**Comment by Seabizkit** [comment]
@JimBobSquarePants 

I am not a tester for you.... I am merely saying that if you resize in v2 its good if you resize in v3 its not.

as of today! latest version, believe it or not but im not here creating test for ImageSharp, i mean im not employed by them either.... but you want A+ level reporting... 

the fact that you think this us lazy... is like OK, say broken... cool. cool cool

you comment is not very professional.. I'm am improving the lib by pointing out there is a regression between version, which clearly has been missed.

wow that was hard... talk about lazy ish
[v3.1.3] and [v2.1.7]

**Comment by tocsoft** [comment]
@Seabizkit I feel that was out of line. Developers in here are doing this unpaid and voluntarily, we are also not here to waste our time trying guess what an issue might be on whatever versions of the codebase you might have deemed worthy to have tried on etc.

What you have done here is not how you get help or how you report issues in this or really any open source community, you be respectful, your provide as much information to allow the people voluntarily giving their time (which they could be spending with their loved ones or anything else).

What is be particularly frustrating is you obviously knew the full version numbers but chose to not be helpful and provide them, you obviously had ran some code to verify there was a difference between both versions that you could have easily copied into to the issue while reporting the issue but chose not to provide that either and (the most critical/actionable piece) you obviously had a versions of the image as you expected them to come out and a version that was broken broken that you had inspected yourself that you could have attached to the issue. Just those 3 small things would have made the issue verifiable and actionable however due to your choices someone (when they can be bothered as incentive will be pretty low at this point to give up their free time) now needs to guess at and try to  reproduce the sample and hope they can break it the same way your trying to report and then go start trying to debug where the error is coming from (all without really knowing is it is the same issue or a different one they might have just found too).

**Comment by Seabizkit** [comment]
my guess is that there are existing test? if not then i would have thought there would be to verify changes between version, iterations.

im merely saying that, with the image i **did provide** that it produces artifacts when going from 1 version to another.

I stated the versions 2 and 3 latest.

"This isn't good enough. You need to actually produce the expected vs actual output and provide code samples.

You haven't even provided version numbers. This is lazy."

"nevermind"lazy  it would be better to say... 

"sorry before i test this in every version could you state the version, even though you said latest, 
I'm not going to check anything unless the version is given. Thanks."

**Comment by JimBobSquarePants** [comment]
There are over 30000 unit tests in this project. 

Respect starts with you abiding by our rules and doing the bare minimum by filling out our issue template correctly. You couldn’t even upload an image demonstrating a potential issue. That’s disrespectful and yes, lazy. 

You talk of professionalism yet cannot do basic tasks expected of a professional. 

You say you are not our tester but forget  also absolutely do not work for you and you are not entitled to anything from us. 

You talk of volunteering time but fail to consider the years of voluntary time dedicated by us to build these libraries. 

You have violated our code of conduct several times now with your argumentative and disrespectful, entitled attitude. You now have the opportunity to apologise and provide appropriate detail or you will be banned from all Six Labors repositories.

**Comment by Seabizkit** [comment]
I apologize , ill close thanks
