### ISSUE TITLE
Padding some PNGs results in reusing colors of the PNG

### ISSUE THREAD

**Issue by PhyxionNL** [SixLabors/ImageSharp#2843]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.6

### Other ImageSharp packages and versions

3.1.6

### Environment (Operating system, version and so on)

Windows

### .NET Framework version

9.0

### Description

```csharp
using (var img = Image.Load(@"test-broken.png"))
{
    img.Mutate(x => x.Resize(new ResizeOptions { Mode = ResizeMode.Pad, Size = new Size(64,64)}));

    img.Save(@"test2.png");
}
```

Top is source, bottom is the destination.

![source](https://github.com/user-attachments/assets/6668df65-c80a-4038-986c-689f760b297f)
![destination](https://github.com/user-attachments/assets/92e4b914-9c7e-4798-bada-25df99d2fb2c)

ImageSharp doesn't add a transparent color around this PNG but reuses some colors from the image itself. I have several more PNGs with this issue.

### Steps to Reproduce

See above.

**Comment by JimBobSquarePants** [comment]
There's no issue here. 

The image provided is an 8bit PNG with a color palette made up of 183 shades of blue. By resizing with padding, you've introduced a new transparent color which doesn't exist in the existing color palette. 

When encoding the encoder will use any existing color table and the transparent region will be encoded using whichever existing color has closest Euclidian distance to transparent. (_Accurate to 5,5,5,6 bits_)

The code is doing exactly what you've told it to do and nothing more. ImageSharp by design it imperative and does not attempt to introduce unknown behavior by guessing user expectations.

In order to make the encoder regenerate a new color palette you need to remove the existing one. 

```c#
using var img2843 = Image.Load<Rgba32>(@"C:\Users\james\Downloads\2843.png");

img2843.Mutate(x => x.Resize(new ResizeOptions { Mode = ResizeMode.Pad, Size = new Size(64, 64) }));

PngMetadata m2843 = img2843.Metadata.GetPngMetadata();
m2843.ColorTable = null;

img2843.SaveAsPng(@"C:\Users\james\Downloads\2843-out.png");

```


![2843](https://github.com/user-attachments/assets/c5ad8f79-1200-4a38-b07e-f6b08fdbc17c)
![2843-out](https://github.com/user-attachments/assets/6484c944-49b6-491c-b0f3-41c2cf2d7a34)

**Comment by PhyxionNL** [comment]
Interesting, thanks!
