### ISSUE TITLE
ICC: es-XL is invalid culture identifier

### ISSUE THREAD

**Issue by ToniaDemchuk** [SixLabors/ImageSharp#304]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When tried to call `Save` after `AutoOrient` method for processing one of JFIF image, got exception:
_System.Globalization.CultureNotFoundException: Culture is not supported. Parameter name: name es-XL is an invalid culture identifier._

Stack trace:
```
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at ImageSharp.IccDataReader.ReadMultiLocalizedUnicodeTagDataEntry()
   at ImageSharp.IccDataReader.ReadTagDataEntry(IccTagTableEntry info)
   at ImageSharp.IccReader.ReadTagData(IccDataReader reader)
   at ImageSharp.IccReader.ReadTagData(Byte[] data)
   at ImageSharp.IccProfile.InitializeEntries()
   at ImageSharp.IccWriter.Write(IccProfile profile)
   at ImageSharp.Formats.JpegEncoderCore.WriteIccProfile(IccProfile iccProfile)
   at ImageSharp.Formats.JpegEncoderCore.WriteProfiles[TPixel](Image`1 image)
   at ImageSharp.Formats.JpegEncoderCore.Encode[TPixel](Image`1 image, Stream stream)
   at ImageSharp.Formats.JpegEncoder.Encode[TPixel](Image`1 image, Stream stream)
   at ImageSharp.Image`1.Save(Stream stream, IImageEncoder encoder)
   at ImageSharp.Image`1.Save(Stream stream, IImageFormat format)
```

### System Configuration

- ImageSharp version: 1.0.0-alpha9-00175
- Environment (Operating system, version and so on): Windows 10, Azure web app on windows platform
- .NET Framework version: NetCore 1.1

**Comment by JimBobSquarePants** [comment]
Hi @ToniaDemchuk This is an interesting exception.

`es-XL` is not a known culture according to the following code.

``` csharp
var cultures = CultureInfo.GetCultures(CultureTypes.AllCultures);
string[] names = cultures.Select(c => c.Name).ToArray();
```

What happens when you create a `CultureInfo` instance using the value on your test machine? On mine it falls back to `es` which I would expect from the following notes.

#### Notes to Callers:
The .NET Framework 3.5 and earlier versions throw an ArgumentException if name is not a valid culture name. Starting with the .NET Framework 4, this constructor throws a CultureNotFoundException. Starting with apps that run under the .NET Framework 4 or later on Windows 7 or later, the method attempts to retrieve a CultureInfo object whose identifier is name from the operating system; if the operating system does not support that culture, and if name is not the name of a supplementary or replacement culture, the method throws a CultureNotFoundException exception.

I can tweak the code to try and load the language code only but I want to be sure of the exception first. Is it a `CultureNotFoundException`

Cheers

James

**Comment by ToniaDemchuk** [comment]
Hello @JimBobSquarePants,

Thanks you for quick reply.
The exception is of type `System.Globalization.CultureNotFoundException`

**Comment by JBildstein** [comment]
@JimBobSquarePants I just added two more cases to the existing tests (with es-XL and xy-XL) but running them normally in Visual Studio they pass as expected since I'm on Windows 10.
How can we ensure that the tests catch this error?

In any case, if you want I can do the fix with catching the `CultureNotFoundException`.
I'd say if that happens, we assign `InvariantCulture` as it's already done if no culture is given.

**Comment by JimBobSquarePants** [comment]
No worries Tonia, :smile:

Johannes, if you wanna PR with tests that would be great! :+1:

What I think would be the best fix would be to fall back to the language code first since that is what Windows 10 does. if that doesn't parse, then fall back to invariant
