### ISSUE TITLE
Rotation output quality isn't very nice

### ISSUE THREAD

**Issue by alex-birch** [SixLabors/ImageSharp#31]
Hi,

It looks like there's no interpolation happening for rotation - can I add that in as a feature request? The quality of images, when rotated by arbitrary degrees, are quite poor.

Thanks,

**Comment by JimBobSquarePants** [comment]
Hi Alex, 

I actually had a version that was interpolating the result but it didn't seem to make much a difference with the output. 

I'll try again some time but it's not high on the priority list just now. Maybe someone from the community can step up.

Cheers

James

**Comment by JimBobSquarePants** [comment]
I had another go. 

https://github.com/JimBobSquarePants/ImageSharp/commit/b168a1d766330e333fc4ba24756b184d81f999e6

Output is still exactly the same as before. Answers on a postcard..... 😖

**Comment by alex-birch** [comment]
Thanks for the update James.

I had to move on to OpenCV and C++ to get what I needed. By using bicubic
there it definitely did a good job of rotation.

Aside from the rotation - we were happily using c# and your library.

thanks again,

**Comment by JimBobSquarePants** [comment]
No worries.... I'll crack it eventually.

**Comment by georgexcollins** [comment]
Just to check my understanding of the ResamplingWeightedProcessor: you can cheaply calculate the fractional offset of destination pixel when translated from source, because for a resize the horizontal offset is the same for every pixel in a column, and the vertical offset is the same for every pixel in a row. Is that correct?
For a rotation, this is not the case, every pixel has a different fraction of a pixel overlap when translated from source to destination image. Don't we have to calculate the interpolation weights for every pixel (in the pixel loop)?

**Comment by JimBobSquarePants** [comment]
@alex-birch It's been almost a year but I've finally cracked it!
