### ISSUE TITLE
Aliasing the using directive causes missing methods

### ISSUE THREAD

**Issue by prw56** [SixLabors/ImageSharp#353]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Aliasing a using directive (as in: using IS = ImageSharp) causes some methods to be missing from the Image class (like the GaussianBlur method). I noticed that missing methods were defined in partial classes, so maybe that has something to do with it.

**Comment by JimBobSquarePants** [comment]
Hi @prw56 

Are you sure you're using the latest version? `GuassianBlur` etc do not live on the image class in beta1. 

Could you provide version numbers?

**Comment by JimBobSquarePants** [comment]
Hello?!

**Comment by prw56** [comment]
Sorry, I was using whatever the default version distributed by nuget is. The only version I see listed on the nuget page is 1.0.0-beta0001, so I assume it is that one.

**Comment by JimBobSquarePants** [comment]
No worries, like I said, those methods are not members of the image class anymore. You need to use the `Mutate` or `Clone` methods to access them.

**Comment by prw56** [comment]
I think I actually tried 2 different versions, because I remember initially using Mutate, then switching to using GaussianBlur. I think the problem still existed for both versions though, any methods defined in partial classes were not visible.

**Comment by JimBobSquarePants** [comment]
Would it be possible for you to upload a replicable sample, please? I don't understand how this could be possible.

Thanks!

**Comment by antonfirsov** [comment]
@prw56 are you sure you're using Mutate/Clone properly? Have you read [this blogpost](https://sixlabors.com/blog/announcing-imagesharp-beta-1/)?

**Comment by JimBobSquarePants** [comment]
I figured it out....

You're not supposed to use using aliases for namespaces, they're for classes. 

e.g.

`using IS = SixLabors.ImageSharp` is incorrect.

`using IS = SixLabors.ImageSharp.Image` is correct.

**Comment by prw56** [comment]
@antonfirsov I'm certain I was using it correctly, b/c the method was present and the code worked when I did not alias the namespace.

@JimBobSquarePants Why is it not correct to alias entire namespaces? Its valid C# syntax and I can still reference the proper classes by prefixing them with the alias (e.g. IS.Image).

**Comment by tocsoft** [comment]
@prw56 its not a case if it being incorrect to alias a namespaces its just not going to work (easily) for you due to the way we deigned our APIs.

Our API is build around extension methods, explicitly so that it can be easily expanded upon by third party developers in a first class manor, but as extension methods are only available (as extensions) if you have the correct using statement included in context (and not aliased) then to use the API as we have designed it requires you to add `using SixLabors.ImageSharp`.

If for some reason you really can't/wont add a full (non-aliasing) using statement then you will have to leverage the static classes directly.
for example the following 2 items are extactly the same minus the use or extension methods or not.
### without using statement
```c#
ImageExtensions.Mutate(img, ctx=>{
   var nextCtx = ImageExtensions.GuassianBlur(ctx, ...);
   nextCtx = ImageExtensions.Operation2(nextCtx, ...);
   nextCtx = ImageExtensions.Operation3(nextCtx, ...);
});
```

### with using statement
```c#
img.Mutate(ctx=>ctx.GuassianBlur(...)
                                .Operation2(...)
                               .Operation3(...));
```

as you can see using it as we designed it is much more readable and maintainable.

**Comment by tocsoft** [comment]
Also closing this as its not actually an issue with ImageSharp but a side effect of how extension methods are handled in c# as a language.
