### ISSUE TITLE
1bpp Support?

### ISSUE THREAD

**Issue by fdncred** [SixLabors/ImageSharp#388]
I can't find any support for bitonal 1bpp support. Is that correct? If so, are there plans to add support?

**Comment by antonfirsov** [comment]
@fdncred unfortunately, it's not possible to define pixel types with size below 1byte with our current architecture. We may consider it for `2.0`. However, we have a
May I ask you about your use case and goal? Maybe there is a workaround for you :)

**Comment by antonfirsov** [comment]
I mean: a custom pixel type with bi-level behavior (but 8bpp physical memory density) might be good enough for you.

**Comment by fdncred** [comment]
Most SDKs/APIs do 24bpp and 32bpp, sometimes 8bpp, rarely 1bpp. In my environment we process millions of 1bpp images daily. I'm always looking for a better, faster, cheaper way to do image processing. Things from simple image processing like rotate and crop to more extravagant convolutional image processing, fourier, blob/connected component, histograms, computer vision, etc. I'd rather process what I can bitonally versus scaling up to 24bpp/32bpp in order to use other SDKs.  Speed is king with accuracy a close second.

**Comment by antonfirsov** [comment]
If your primary goal is processing speed, those 8-32bpp pixel formats perform better usually, because you have to run less packing/unpacking operations.
I'm not saying that it's impossible to do those processing operations efficiently with 1bpp, but it's really hard, and it is a very specific area. Our engine is usually packing/unpacking pixel rows into `Vector4` (`_m128`) blocks before doing the processing work. This way we can keep our code accurate, relatively fast (SIMD-optimized), but still readable.

**Comment by fdncred** [comment]
Thanks for the info.
