### ISSUE TITLE
Refactor solution namespaces and classes

### ISSUE THREAD

**Issue by JimBobSquarePants** [SixLabors/ImageSharp#401]
### Problem

Currently most of the existing types are located within a flat namespace `SixLabors.ImageSharp`. Many of our extension methods share a single class `ImageExtensions`.

This is detrimental for several reasons:

- Discoverability. Having all the types in a single namespace pollutes intellisense.
- Bugs. Using classes with the same name and namespace in both `ImageSharp` and `ImageSharp.Drawing` causes ambiguous reference issues #391
- Documentation. With clustered method sharing single namespaces and classes we are unable to produce meaningful API documentation using automated means. 

### Solution

Tackling this problem requires some significant refactoring to the solution and tests.

- Refactor extensions and processors into individual namespaces grouped by their operation function. For example:
  - Transforms
  - Effects
  - Convolution
  - Drawing
- Separate the static extension method classes into individual classes. For example: 
  - Resize
  - Crop 
  - Rotate
- Change root namespace for `ImageSharp.Drawing` from `SixLabors.ImageSharp` to `SixLabors.ImageSharp.Drawing` and perform similar refactorings there where necessary.

### Potential Issues

Any open PR's will likely have merging issues after this change. We should strive to close any that we possible can before work commences.

**Comment by rspeele** [comment]
Just want to let you know this might be more important than you think.

I'm in .NET framework land, so it might be different on Core. But as far as I can tell, the ambiguous references make it **impossible** to call `ImageExtensions` methods from any code that references `SixLabors.ImageSharp.Drawing`.

I know in #391 you suggested this was due to calling the methods as regular old static methods instead of using the extension method syntax, but in my experience it doesn't work either way -- you just get a less helpful, more misleading error using the extension method syntax (which of course normally I would use).

#### Example

I make a console app targeting framework 4.5.2 (I doubt the framework version matters though).
I install nightly:

```
Install-Package SixLabors.ImageSharp -Version 1.0.0-dev000733 -Source https://www.myget.org/F/sixlabors/api/v3/index.json 
```

I write this code:

```csharp
using SixLabors.ImageSharp;

namespace Foo
{
    class Program
    {
        static void Main(string[] args)
        {
            var image = Image.Load(new byte[0]);
            image.Resize(0, 0);
        }
    }
}
```

It doesn't compile.

```
error CS1061: 'Image<Rgba32>' does not contain a definition for 'Resize' and no extension method 'Resize' accepting a first argument of type 'Image<Rgba32>' could be found (are you missing a using directive or an assembly reference?)
```

Notice that I *do* have the using directive.
I try invoking the extension method as a static method instead.

```csharp
using SixLabors.ImageSharp;

namespace Foo
{
    class Program
    {
        static void Main(string[] args)
        {
            var image = Image.Load(new byte[0]);
            SixLabors.ImageSharp.ImageExtensions.Resize(image, 0, 0);
        }
    }
}
```

Now the compiler tells me the real reason I can't use `Resize`.

```
error CS0433: The type 'ImageExtensions' exists in both 'SixLabors.ImageSharp.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'SixLabors.ImageSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
```

**Comment by JimBobSquarePants** [comment]
Thanks @rspeele 

Rest assured we'll be refactoring all those issues away and everything will live neatly in their own namespaces for beta3.

Just to note though, we'll probably be dropping netstandard 1.1 support so your NET 4.5.2 program will not be possible, you'll have to bump up to NET 4.6.1
