### ISSUE TITLE
Accessing individual pixel of an image

### ISSUE THREAD

**Issue by asterixorobelix** [SixLabors/ImageSharp#419]
### Description
I'm a bit of a noob, but I am hopefully making up for it by documenting my questions in the wiki: https://github.com/SixLabors/ImageSharp/wiki/Questions-and-Answers

### Steps to Reproduce

Let us say that I have the following code:
```cs
                using (Image<Rgba32> image = Image.Load($"{filename}.png"))
                {
                    var imageHeight = image.Height; //I assume that this is height of the image in pixels?
                    var imageWidth = image.Width;
                    var pixel =image[200,200];//<1  1  1  1>
                    var pixel2 = image[125, 180];//<0.7647059  0.7647059  0.7647059  1>
                }
```
Does imageHeight contain the height of the image in pixels? What is the information contained in pixel2? By the way, it is a black and white image.

**Comment by JimBobSquarePants** [comment]
Hi @asterixorobelix 

I don't know if you read the [Contribution Guidelines](https://github.com/SixLabors/ImageSharp/blob/master/.github/CONTRIBUTING.md) when you raised this and your previous issue but we actually have a [Gitter](https://gitter.im/ImageSharp/General) chatroom for questions. This tracker is for issues only.

In answer to your question. The width and height, represent the width and the height of the image in pixels.

To access the individual pixels you use the indexer as you have demonstrated. The pixel at `[200, 200]` is white and the pixel at `[125, 180]` is grey. 

Those numbers you have posted beside them are the `Vector4` representation of those pixels (each pixel component divided by 255F). I'm not sure how you came up with them other than by calling `ToVector4()` on the index since the `ToString()` representation of the `Rgba32` struct should represent the byte values ranging from 0 - 255. 

I hope that makes sense.

Cheers

James

**Comment by asterixorobelix** [comment]
Thanks James.

Sorry about that, will ask my dumb questions on gitter

**Comment by JimBobSquarePants** [comment]
No such thing as dumb questions. Ask away! 😄
