### ISSUE TITLE
how to get image format from an Image<Rgba32> instance

### ISSUE THREAD

**Issue by endink** [SixLabors/ImageSharp#432]
if use System.Drawing，  Image.RawFormat poperty can do it.

and how to do it, if use Image&lt;Rgba32&gt;

thanks!

**Comment by JimBobSquarePants** [comment]
There's an overload for `Image.Load` that passes an `IImageFormat` as an out parameter which will give you what you need. 

P.S. We have a Gitter channel for questions. 😄

**Comment by habedi77** [comment]
this still does not answer how to get format From Image<Rgba32> when that's only what you have and your method didn't call the load.

**Comment by JimBobSquarePants** [comment]
>this still does not answer how to get format From Image when that's only what you have and your method didn't call the load.

What? This makes no sense.

**Comment by habedi77** [comment]
Assume a function takes an "Image\<Rgba32\>" as input.
How can that function figure out the format of the image?

**Comment by JimBobSquarePants** [comment]
OK I understand now. Thanks.

At some point in your code you will have to load the image. That is when you capture the input format and pass it along to any other methods. We don't capture and hold the `IImageFormat` because it is a shared reference across all images and does more than the System.Drawing `ImageFormat` class which is basically a static class containing predefined identifiers. 

A System.Drawing image has no defined format unless it is loaded from a stream. The format identifier defaults to an empty Guid.

**Comment by habedi77** [comment]
I see.
Thank you.

**Comment by JimBobSquarePants** [comment]
No problem, happy to help.

**Comment by avs099** [comment]
what about LoadAsync()? It does not have this overload

**Comment by avs099** [comment]
well, then you would want to use LoadWithFormatAsync: :)
https://github.com/SixLabors/ImageSharp/blob/d95a996ed5ba14a1421dafeb844a56ab08211ead/src/ImageSharp/Image.FromStream.cs#L427
