### ISSUE TITLE
Find out the number of colors in the image's palette

### ISSUE THREAD

**Issue by gordon-matt** [SixLabors/ImageSharp#488]
Given an `Image<Rgba32>`, how do I find out the number of colors in the image's palette? I am trying to convert some old code using `System.Drawing`:

```
public static int imagecolorstotal(PhpResource im)
{
    PhpGdImageResource img = PhpGdImageResource.ValidImage(im);
    if (img == null)
        return 0;
    
    var format = img.Image.PixelFormat; // <-- img.Image is now an instance of Image<Rgba32>

    if ((format & PixelFormat.Format1bppIndexed) != 0)
        return 2;
    if ((format & PixelFormat.Format4bppIndexed) != 0)
        return 16;
    if ((format & PixelFormat.Format8bppIndexed) != 0)
        return 256;

    if ((format & PixelFormat.Indexed) != 0)
    {
        // count the palette
        try
        {
            // TODO: optimize, cache ?
            return img.Image.Palette.Entries.Length;
        }
        catch
        {
            // ignored, some error during SafeNativeMethods.Gdip.GdipGetImagePalette
        }
    }

    // non indexed image
    return 0;
}
```

**Comment by JimBobSquarePants** [comment]
Hey @gordon-matt 

We don't have the same `PixelFormat` enumeration as System.Drawing as we use whatever the given `TPixel` type parameter is to organize the memory layout we operate in. An image could have been stored in indexed format but with `Rgba32` we operate in a 32bit space.

In our [nightlies](https://github.com/SixLabors/ImageSharp#installation) and soon to be released beta we can help you though.

We have a new property `PixelTypeInfo` on the `IImageInfo` interface (used by both `ImageInfo` and `Image<TPixel>` types) that contains a  property `BitsPerPixel` representing the number of bits per pixel that the original image was stored in. If that value is greater than 8 you know it's not an indexed image.

`(int)(Math.Pow(2, image.PixelFormat.BitsPerPixel)` will give you the palette length.

Incidentally color palettes are usually padded to match the bits per pixel value so your above code might not give an accurate representation of the actual colors. Only a histogram can truly offer you that.

Hope that all makes sense.

Cheers

James

P.S. Questions are really used for the Gitter channel not the Issue tracker, that's why we have the template, contribution guidelines etc.
