### ISSUE TITLE
JpgExport -> System.OverflowException: Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by alex-birch** [SixLabors/ImageSharp#559]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
Closest I could find was [this](https://github.com/SixLabors/ImageSharp/issues/217)

### Description

Loading and export this image as a Jpg ByteArray causes the following stack trace (PNG works okay):

`Unhandled Exception: System.OverflowException: Array dimensions exceeded supported range.
   at SixLabors.ImageSharp.MetaData.Profiles.Icc.IccReader.ReadTagTable(IccDataReader reader)
   at SixLabors.ImageSharp.MetaData.Profiles.Icc.IccReader.ReadTagData(IccDataReader reader)
   at SixLabors.ImageSharp.MetaData.Profiles.Icc.IccProfile.InitializeEntries()
   at SixLabors.ImageSharp.MetaData.Profiles.Icc.IccWriter.Write(IccProfile profile)
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.JpegEncoderCore.WriteIccProfile(IccProfile iccProfile)
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.JpegEncoderCore.Encode[TPixel](Image`1 image, Stream stream)
   at WebApplicationBasic.Program.Main(String[] args) in Program.cs:line 18`

### Steps to Reproduce

![coco_val2014_000000395978](https://user-images.githubusercontent.com/4734530/39688369-bbadfefa-5215-11e8-8c08-e6fa7f16afa5.jpg)

I loaded the image and exported to JPG like so:
`            var img = SixLabors.ImageSharp.Image.Load<Rgba32>(args[0]);
            img.ToByteArray(new JpegEncoder());`

### System Configuration

- ImageSharp version:
SixLabors.ImageSharp 1.0.0-beta0003
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
MacOS High Sierra
- .NET Framework version:
Dotnet 2.1.3
- Additional information:

**Comment by JBildstein** [comment]
I checked out the image and it looks like the ICC data is corrupt (confirmed it with exiftool as well).

@JimBobSquarePants, perhaps we could put some checks in place to exclude corrupt profiles. In this case a look at the header would be enough to filter it out. Reading the header is pretty safe and won't throw an exception even with nonsense data. (except for CreationDate, but there's already a try/catch around it).

**Comment by JimBobSquarePants** [comment]
@JBildstein Was hoping you'd see this. What would be indicative in the header that the profile is corrupt. I'm assuming it's reported length is greater than `Int32.MaxValue`?

**Comment by JBildstein** [comment]
There are several things we could check:
 - FileSignature: should always be set to "acsp", but it's not a hard requirement
 - DataColorSpace and ProfileConnectionSpace: has to be a member of the IccColorSpaceType enum. Custom values don't make any sense here so it's pretty safe to assume corruption.
 - RenderingIntent: can only be 0-3. Could be a custom value (very very unlikely though and not allowed by the specs afaik)
 - PcsIlluminant: it's an XYZ color so valid values are usually in the range of 0-1.x, anything bigger than two can probably be seen as invalid

I wouldn't include length in the checks because a large number of values could be valid, e.g. from a couple dozen bytes to several MB. We could check for zero though, most checks above would report a valid value if the data is zeroed out, but a zero length doesn't make sense.

My suggestion would  be to always check if FileSignature is "acsp" and if that fails, perform the other checks to make sure. I don't know when it'd be best to perform the check though (and handle it).
