### ISSUE TITLE
EXIF units in JPEG are ignored if JFIF resolution is present.

### ISSUE THREAD

**Issue by maxvoxel8** [SixLabors/ImageSharp#745]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
If I try to load a JPEG image where the units are set in the EXIF but not in the JFIF section, it ignores the units. It seems that Pixelmator sets the units in the EXIF but not the JFIF section.

It is apparent from the lines below that if JFIF data is present, EXIF data is ignored. 
https://github.com/SixLabors/ImageSharp/blob/ff7089080548b165b430bd79d774b3a3725b3dc4/src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs#L454-L471

### Steps to Reproduce
Load this image: 

![test_square](https://user-images.githubusercontent.com/13626626/47396233-f5913300-d6f7-11e8-85d0-d654ee90ec58.jpg)

And check image.MetaData.ResolutionUnits.

### System Configuration

- ImageSharp version: 1.0.0-dev001898
- Other ImageSharp packages and versions: 
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.5
- Additional information:

**Comment by JimBobSquarePants** [comment]
The problem we have here is that the image itself is incorrectly encoded by Pixelmator.

The ratio should be set correctly as part of the JPEG File Interchange Format Version 1.02 specification.

![incorrect ratio](https://user-images.githubusercontent.com/385879/47467093-703b7a80-d7ec-11e8-8ca2-ee5813d10d04.png)

I believe we should be following the ratio as defined in the JFIF APP0 marker explicitly since EXIF metadata is supplementary. I would suggest raising this with Pixelmator.
